#!/usr/bin/env ruby
require "yaml"

refs = {}
YAML.load($stdin.read).each do |entry|
  # entry has en, id, ja
  ja = entry["ja"]
  refs[ja] and raise "duplicated entry: #{entry.inspect}"
  refs[ja] = entry["id"]
end
puts YAML.dump(refs)
