name: Build and deploy to GitHub Pages
on:
  push:
    branches: [ "ja" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --yes \
            lua5.3 \
            luarocks \
            liblua5.3-dev \
            libyaml-dev \
            libcmark-dev \
            cpanminus \
            po4a

      - name: Install CommonMark Perl module
        run: |
          sudo cpanm CommonMark

      - name: Install LuaRocks
        run: |
          ./translation/bin/install

      - name: Build pages
        run: |
          eval "$(luarocks path --bin)"
          git clone https://github.com/mquinson/po4a
          export PERL5LIB="$PWD/po4a/lib:$PERL5LIB"
          export PATH="$PWD/po4a:$PATH"
          ./translation/bin/translate
          mkdir -p tmp-for-github-pages
          while IFS= read -r code
          do
              case $code in
                  '#'*|'') continue ;;
              esac
              mv "translation/build/$code/spec.html" \
                 "tmp-for-github-pages/spec.$code.html"
          done < translation/LINGUAS

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tmp-for-github-pages

  deploy:
    if: github.ref == 'refs/heads/ja'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
